name: AI PR Review

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch: {}

# Least-privilege token: read code, write PR review
permissions:
  contents: read
  pull-requests: write

jobs:
  AI-PR-Review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: |
          npm ci || npm i

      - name: Run AI review
        env:
          GITHUB_TOKEN: ${{ github.token }}
          LLM_PROVIDER: ${{ secrets.LLM_PROVIDER }} # openai | openrouter | ollama
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
          # OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }} # optional proxy/base URL
          MODEL: ${{ secrets.MODEL }}
          MAX_TOKENS: ${{ secrets.MAX_TOKENS }}
          TEMPERATURE: ${{ secrets.TEMPERATURE }}
          FILE_GLOBS: |
            src/**
            app/**
            lib/**
            **/*.{ts,tsx,js,jsx,py,go,rb,java,cs}
        run: |
          node ./scripts/ai-review.js
